// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiL_mrPM2_WLjnY6EC5IFEjMENRpIB_g8',
    appId: '1:362014050175:web:0b0542f163ee3bb613fc4a',
    messagingSenderId: '362014050175',
    projectId: 'authproj-8cadd',
    authDomain: 'authproj-8cadd.firebaseapp.com',
    storageBucket: 'authproj-8cadd.appspot.com',
    measurementId: 'G-VL6W5HEMR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe5lWtW5IpG0feYBhtih7AchiYTmAsa-Y',
    appId: '1:362014050175:android:8c93b4574ef1d0ef13fc4a',
    messagingSenderId: '362014050175',
    projectId: 'authproj-8cadd',
    storageBucket: 'authproj-8cadd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCer4IKQvcbL4qvRoyvBZSFZPSCmHW_8Yc',
    appId: '1:362014050175:ios:efe3c81e7b4849a813fc4a',
    messagingSenderId: '362014050175',
    projectId: 'authproj-8cadd',
    storageBucket: 'authproj-8cadd.appspot.com',
    iosBundleId: 'com.example.rebuyproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCer4IKQvcbL4qvRoyvBZSFZPSCmHW_8Yc',
    appId: '1:362014050175:ios:efe3c81e7b4849a813fc4a',
    messagingSenderId: '362014050175',
    projectId: 'authproj-8cadd',
    storageBucket: 'authproj-8cadd.appspot.com',
    iosBundleId: 'com.example.rebuyproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiL_mrPM2_WLjnY6EC5IFEjMENRpIB_g8',
    appId: '1:362014050175:web:3697ba643ef8dc0e13fc4a',
    messagingSenderId: '362014050175',
    projectId: 'authproj-8cadd',
    authDomain: 'authproj-8cadd.firebaseapp.com',
    storageBucket: 'authproj-8cadd.appspot.com',
    measurementId: 'G-WGMZ9JYWTW',
  );
}
